version: '2.3'

x-lagoon-project:
  &lagoon-project govcms8-saas

x-lagoon-local-dev-url:
  &lagoon-local-dev-url http://govcms8-saas.docker.amazee.io

x-govcms-image-version:
  &govcms-image-version ${GOVCMS_IMAGE_VERSION:-latest}

x-volumes:
  &default-volumes
    volumes:
      - ./themes:/app/web/themes/custom:${VOLUME_FLAGS:-delegated}
      - ./files:/app/web/sites/default/files:delegated
      - ./tests/behat/features:/app/tests/behat/features:${VOLUME_FLAGS:-delegated}
      - ./tests/phpunit/tests:/app/tests/phpunit/tests:${VOLUME_FLAGS:-delegated}
      - ./config:/app/config

x-environment:
  &default-environment
    STAGE_FILE_PROXY_URL: ${STAGE_FILE_PROXY_URL:-}
    LAGOON_ENVIRONMENT_TYPE: ${LAGOON_ENVIRONMENT_TYPE:-}
    LAGOON_PROJECT: *lagoon-project
    LAGOON_ROUTE: &default-url ${LOCALDEV_URL:-http://govcms8-saas.docker.amazee.io}
    GOVCMS_IMAGE_VERSION: ${GOVCMS_IMAGE_VERSION:-latest}
    DEV_MODE: ${DEV_MODE:-false}
    X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}
    # Allow to override docker host used from the inside of the containers.
    DOCKERHOST: ${DOCKERHOST:-}
    XDEBUG_ENABLE: ${XDEBUG_ENABLE:-}

services:

  cli:
    build:
      context: .
      dockerfile: .docker/Dockerfile.cli
      args:
        GOVCMS_IMAGE_VERSION: *govcms-image-version
    image: *lagoon-project
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx
      lagoon.persistent: /app/web/sites/default/files/
    << : *default-volumes
    environment:
      << : *default-environment

  test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.test
      args:
        GOVCMS_IMAGE_VERSION: *govcms-image-version
    labels:
      lagoon.type: none
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: *lagoon-project
        GOVCMS_IMAGE_VERSION: *govcms-image-version
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/web/sites/default/files/
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: *default-url
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        CLI_IMAGE: *lagoon-project
        GOVCMS_IMAGE_VERSION: *govcms-image-version
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx
      lagoon.persistent: /app/web/sites/default/files/
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  mariadb:
    image: ${MARIADB_DATA_IMAGE:-govcms8lagoon/mariadb-drupal}
    labels:
      lagoon.type: mariadb
      lagoon.image: govcms8lagoon/mariadb-drupal
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  # Lodge a support ticket to have Redis enabled.
  # redis:
  #   image: govcms8lagoon/redis
  #   labels:
  #     lagoon.type: redis
  #   environment:
  #     << : *default-environment

  # Lodge a support ticket to have Solr enabled.
  # solr:
  #   image: govcms8lagoon/solr
  #   labels:
  #     lagoon.type: solr
  #   ports:
  #     - "8983" # Find port on host with `docker-compose port solr 8983`
  #   environment:
  #     << : *default-environment

  chrome:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    depends_on:
      - test
    labels:
      lagoon.type: none
    << : *default-volumes

networks:
  amazeeio-network:
    external: true
