FROM govcms8lagoon/govcms8

COPY themes/ /app/web/themes/custom
COPY config /app/config

# Default application favicon this will be used for files and server
# error pages all other favicon requests will be surfaced via Drupal.
COPY favicon.ico /app/web
